airflow_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: dbt
      threads: 4

bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_BQ_DATASET') }}"
      keyfile: "{{ env_var('GCP_KEYFILE_PATH') }}"
      threads: 4
